service: monkeybusiness-mastodon-en
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  region: eu-central-1

functions:
  mibot:
    handler: handler.mibot
    environment:
      ACCESS_TOKEN: ${ssm:/mibot_mastodon_en_access_token}
      API_URL: ${ssm:/mibot_mastodon_de_api_url}
    timeout: 60
    events:
      - schedule: cron(0 * * * ? *)